### ISSUE TITLE
Check compatibility with ext_solr 3.1.0

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solrgrouping#2]
We need to check the compatibility with ext_solr 3.1.0

**Comment by irnnr** [comment]
Should work AFAIK

**Comment by timohund** [comment]
I've checked it and in the classic mode it worked but not in composer mode. In my branch i've added a composer.json file (with name: apache-solr-for-typo3/solrgrouping) in the same style as of tx_solr and made the classes PSR-4 compatible.

What do you think?

**Comment by irnnr** [comment]
Good catch, that was still open since I don't use a case sensitive file system

**Comment by timohund** [comment]
Thx for merging. Can we also add a packagist project?
